<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8499" started-at="2017-08-31T19:05:50Z" finished-at="2017-08-31T19:05:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8499" started-at="2017-08-31T19:05:50Z" finished-at="2017-08-31T19:05:58Z">
      <class name="runTestCases.TestDragAndDrop">
        <test-method status="PASS" signature="setUp()[pri:0, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="setUp" is-config="true" duration-ms="2839" started-at="2017-08-31T16:05:50Z" finished-at="2017-08-31T16:05:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="dragAndDrop()[pri:0, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="dragAndDrop" duration-ms="87" started-at="2017-08-31T16:05:53Z" finished-at="2017-08-31T16:05:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragAndDrop -->
        <test-method status="FAIL" signature="dragAndDrop2()[pri:1, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="dragAndDrop2" duration-ms="43" started-at="2017-08-31T16:05:53Z" finished-at="2017-08-31T16:05:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testCases.TestHTML5DragDrop.testDragAndDrop2(TestHTML5DragDrop.java:42)
	at runTestCases.TestDragAndDrop.dragAndDrop2(TestDragAndDrop.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragAndDrop2 -->
        <test-method status="PASS" signature="dragAndDrop3()[pri:2, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="dragAndDrop3" duration-ms="40" started-at="2017-08-31T16:05:53Z" finished-at="2017-08-31T16:05:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragAndDrop3 -->
        <test-method status="PASS" signature="dragAndDrop4()[pri:3, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="dragAndDrop4" duration-ms="38" started-at="2017-08-31T16:05:53Z" finished-at="2017-08-31T16:05:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragAndDrop4 -->
        <test-method status="FAIL" signature="dragAndDrop5()[pri:4, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="dragAndDrop5" duration-ms="41" started-at="2017-08-31T16:05:53Z" finished-at="2017-08-31T16:05:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testCases.TestHTML5DragDrop.testDragAndDrop5(TestHTML5DragDrop.java:78)
	at runTestCases.TestDragAndDrop.dragAndDrop5(TestDragAndDrop.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragAndDrop5 -->
        <test-method status="PASS" signature="testW3SchoolsDragAndDrop()[pri:5, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="testW3SchoolsDragAndDrop" duration-ms="5294" started-at="2017-08-31T16:05:53Z" finished-at="2017-08-31T16:05:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testW3SchoolsDragAndDrop -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:runTestCases.TestDragAndDrop@64bfbc86]" name="tearDown" is-config="true" duration-ms="98" started-at="2017-08-31T16:05:58Z" finished-at="2017-08-31T16:05:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- runTestCases.TestDragAndDrop -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
